name: release
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

  publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: 安装最新版本npm cli 用于OIDC提交
        run: npm install -g npm@latest

      - name: 安装开发依赖
        run: pnpm install

      - name: 构建产物
        run: pnpm run build

      - name: 禁用 git 检查
        run: pnpm config set git-checks false

      - name: 发布 npm 包
        run: pnpm publish --access public

      - name: 同步到 npmmirror 镜像
        run: pnpm run sync
